### ISSUE TITLE
zipfile.BadZipFile error during wacz creation from warc file - Windows only

### ISSUE THREAD

**Issue by ivbeg** [webrecorder/py-wacz#18]
![изображение](https://user-images.githubusercontent.com/203209/160269302-06e426d0-5e33-4981-b74c-100ad5f1f807.png)

I see following error each time when I use latest py-wacz on Windows
_Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\wacz.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\wacz\main.py", line 109, in main
    value = cmd.func(cmd)
  File "C:\Program Files\Python310\lib\site-packages\wacz\main.py", line 320, in create_wacz
    datapackage = wacz_indexer.generate_datapackage(res, wacz)
  File "C:\Program Files\Python310\lib\site-packages\wacz\waczindexer.py", line 343, in generate_datapackage
    with wacz.open(zip_entry, "r") as stream:
  File "C:\Program Files\Python310\lib\zipfile.py", line 1545, in open
    raise BadZipFile(
zipfile.BadZipFile: File name in directory 'archive\\cafrussia.ru.warc' and header b'archive/cafrussia.ru.warc' differ._

Environment: Windows 10, Python 3.10.0, wacz 0.4.5

No error happens on Linux or in the Windows Subsystem for Linux envrionment.

**Comment by gwiedeman** [comment]
I looked into this and I think the issue may be related to upstream Windows path-handling bugs in Python’s `zipfile` module, probably related to [this issue](https://github.com/python/cpython/issues/94529). The behavior seems to involve `ZipInfo.from_file()` and how archive paths are normalized on Windows. Py-wacz could write its own `zip_info_from_file()` but this is probably bad practice for sustainability sake and it should probably get addressed upstream.
